server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
  rabbitmq:
    connection-timeout: 1s # 设置MQ的连接超时时间
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: false # 开启publisher return机制
    listener: # 消費者
      simple:
        acknowledge-mode: none # 消費者確認機制。none、manual、auto（在消費者端生效）
        retry:
          enabled: true # 开启超时重试机制
          initial-interval: 1000ms # 失败后的初始等待时间
          multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
          max-attempts: 3 # 最大重试次数
          stateless: true # 失敗重試機制：【true无状态；false有状态。如果业务中包含事务，这里改为false】
    template: # 生產者
      mandatory: false
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数


hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
#server:
#  port: 8085
#spring:
#  application:
#    name: trade-service
#  cloud:
#    nacos:
#      server-addr: 192.168.76.138:8848
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://${hm.db.host}:3306/hm-trade?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${hm.db.pw}
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  level:
#    com.hmall: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#knife4j:
#  enable: true
#  openapi:
#    title: 交易服务接口文档
#    description: "信息"
#    email: zhanghuyi@itcast.cn
#    concat:
#    url: https://www.itcast.cn
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.hmall.trade.controller
#feign:
#  okhttp:
#    enabled: true